// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	model "exercise-login-back-go/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: user
func (_m *UserRepository) CreateUser(user model.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserByEmailOrPhone provides a mock function with given fields: email, Phone
func (_m *UserRepository) GetUserByEmailOrPhone(email string, Phone string) (*model.User, error) {
	ret := _m.Called(email, Phone)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmailOrPhone")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.User, error)); ok {
		return rf(email, Phone)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.User); ok {
		r0 = rf(email, Phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, Phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmailOrUsername provides a mock function with given fields: emailOrUsername
func (_m *UserRepository) GetUserByEmailOrUsername(emailOrUsername string) (*model.User, error) {
	ret := _m.Called(emailOrUsername)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmailOrUsername")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return rf(emailOrUsername)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(emailOrUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(emailOrUsername)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
